### PR TITLE
QGCS utm adapter high level design

### PR DESCRIPTION
**Pull request by govindsi**
This PR adds high level design files(drawio) and images(*jpg) for QGCS UTM adapter integration work.

- UTM adapter QGC System Integration Architecture
- UTM adapter QGC Flight Authorization Flow
- UTM adapter QGC Network RemoteID Flow
- UTM adapter QGC SITL Flow

### CODE REVIEW

**Comment by hrishiballal** [comment]
Hello @govindsi, thank you for this, some comments:

In qgcs-hld/images/UTM-adapter-QGC-System-Architecture.jpg
	- To right, USSP is a EU term, you can call it UTM System Flight plan flow 
	- Left rename OpenUTM USSP to OpenUTM / UTM services
	- Rename Upload Mission -> Upload mission to vehicle 
	- There is a activation step before telemetry submission

In qgcs-hld/images/UTM-adapter-QGC-SITL-flow.jpg:
	- Right hand recommend rename Flight Blender USSP to "OpenUTM / UTM service provider"
	- Recommend renaming USSP Link - > UTM Adapter

In qgcs-hld/images/UTM-adapter-QGC-Network-RemoteID-Flow.jpg:
	- Rename UI to QGCS UI 
	- Recommend renaming USSP (FB) -> "OpenUTM / UTM service provider"
	- Rename USSP (FB) to OpenUTM and USSP (AMQP) to OpenUTM (AMQP channel) 
	- Perhaps have a dotted line to show what is inside the QGCS methods USSP* 

In qgcs-hld/images/UTM-adapter-QGC-Flight-Authorization-Flow.jpg:
	- Rename USSP Toolbar : UTM toolbar 
	- Same as above the internal QGCS methods USSP* should be in a dotted line
	- Same as above: USSP (FB) -> "OpenUTM / UTM service provider"
	- Same box as rid flow (right) that encompasses the USSP functions

**Comment by hrishiballal** [comment]
Also recommend instead of naming the directory as `qgcs-hld` rename to `utm-adapter-architecture-diagrams` or `utm-adapter-data-flow` or something similar

**Comment by govindsi** [comment]
> Hello @govindsi, thank you for this, some comments:
> 
> In qgcs-hld/images/UTM-adapter-QGC-System-Architecture.jpg - To right, USSP is a EU term, you can call it UTM System Flight plan flow - Left rename OpenUTM USSP to OpenUTM / UTM services - Rename Upload Mission -> Upload mission to vehicle - There is a activation step before telemetry submission
> 
> In qgcs-hld/images/UTM-adapter-QGC-SITL-flow.jpg: - Right hand recommend rename Flight Blender USSP to "OpenUTM / UTM service provider" - Recommend renaming USSP Link - > UTM Adapter
> 
> In qgcs-hld/images/UTM-adapter-QGC-Network-RemoteID-Flow.jpg: - Rename UI to QGCS UI - Recommend renaming USSP (FB) -> "OpenUTM / UTM service provider" - Rename USSP (FB) to OpenUTM and USSP (AMQP) to OpenUTM (AMQP channel) - Perhaps have a dotted line to show what is inside the QGCS methods USSP*
> 
> In qgcs-hld/images/UTM-adapter-QGC-Flight-Authorization-Flow.jpg: - Rename USSP Toolbar : UTM toolbar - Same as above the internal QGCS methods USSP* should be in a dotted line - Same as above: USSP (FB) -> "OpenUTM / UTM service provider" - Same box as rid flow (right) that encompasses the USSP functions

Thank you for the valuable comments! Updated.

**Comment by govindsi** [comment]
> Also recommend instead of naming the directory as `qgcs-hld` rename to `utm-adapter-architecture-diagrams` or `utm-adapter-data-flow` or something similar

Updated.

**Pull request merged**
